version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db-network
    
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
      - db-network
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mydatabase;Username=admin;Password=admin;

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
  nginx-proxy:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
    networks:
      - sonarnetwork
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    networks:
      - sonarnetwork

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=sonarqube:9000
      - NGROK_AUTHTOKEN=2g4tX5fTrlqp6ThkbZqb5sYxLB7_4GXZAW7vS4zJFF2EX9fRi
    depends_on:
      - sonarqube

volumes:
  postgres-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
  sonarnetwork:
    driver: bridge