name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        entryPoint: msbuild
        args: >-
          /d:sonar.login=sqp_d6aa0acaeaf797fc545c4e6c12e775ff705c0201
          /d:sonar.projectKey=real-estate-dashboard
          /d:sonar.projectName='Real Estate Dashboard'
          /d:sonar.projectVersion=1.0
          /d:sonar.host.url=http://localhost:9000
          /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          /d:sonar.coverage.exclusions=**/Migrations/**,**/bin/**,**/obj/**,**/Views/**,**/*.Designer.cs
