name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        entryPoint: msbuild
        args: >-
          /d:sonar.login=squ_1566da8da6a9ea97a43b184dea0f108a2a8090a6
          /d:sonar.projectKey=your_project_key
          /d:sonar.projectName='Your Project Name'
          /d:sonar.projectVersion=1.0
          /d:sonar.host.url=http://localhost:9000
          /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          /d:sonar.coverage.exclusions=**/Migrations/**,**/bin/**,**/obj/**,**/Views/**,**/*.Designer.cs
